### ISSUE TITLE
$cc add doesn't work for 2 word nicknames

### ISSUE THREAD

**Issue by Shepherdwhen** [WerewolvesRevamped/Werewolves-Bot#43]
$cc add name doesn't work for 2 word names

in the example $cc add torch ginger didn't work but $cc add 🎐 did

![image](https://github.com/McTsts/Werewolves-Bot/assets/82595414/f8f3992a-c0d2-4e91-90e9-f085b0efcf36)

**Comment by McTsts** [comment]
I might be misunderstanding but I did:

 $cc add flute player 
 
 here and it works
 
 So I think this has been fixed
 
![image](https://github.com/user-attachments/assets/69e0bb50-aa62-4a8e-bea3-d5d1ca7e7ac1)
